### PR TITLE
Add User registration form validation and call register user api.

### LINKED ISSUE #4: Add Register Page
This is fairly an easy task, I want you to add a Register Page below Login Button. Please make it identical with the login page

The fields are Name, Username, and Password. Check out the UserModel I have. For the endpoint, it's /api/user/register

Thanks

### PR DESCRIPTION
**Pull request by ashwinimanoj**
Should close #4.

Also, there should be a way to handle the scenario when a username exists, right now it returns with a 500 error.

### CODE REVIEW

**Comment by dennypradipta** [comment]
Oh, form validation is just like that in React. TIL.

For the username, the model has that index: { unique: true } so I think it prevented duplicate username. But I suppose there is should custom error messages if it's duplicate username.

Looking pretty good, merged now.

Thank you for your contribution, so far. It's the 4th PR I've merged from you :)

**Comment by ashwinimanoj** [comment]
@dennypradipta Thank you! I am happy to hear that! :)

**Comment by ashwinimanoj** [comment]
@dennypradipta , I was wondering why this has not been merged? Is there something I missed?

**Comment by dennypradipta** [comment]
Oh my god, I am so sorry. I thought I merged this. I merged it now. Looks like I was half sleeping while processing this. Thank you for reminding me and soooo sorry!

**Comment by ashwinimanoj** [comment]
That's okay :D Thanks!

**Pull request merged**
